version: "3.7"
services:
 app:
  build:
   args:
    user: jonas
    uid: 1000
   context: ./
   dockerfile: Dockerfile
  image: gest-filas
  container_name: gest-filas-app
  restart: unless-stopped
  working_dir: /var/www/
  volumes:
   - ./:/var/www
  networks:
   - gest-filas

 db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    container_name: gest-filas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - gest-filas

 nginx:
    image: nginx:1.17-alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - gest-filas

networks:
  gest-filas:
    driver: bridge
